package tid.controlador;

//CLASE PARA DEFINICION DE LOS STRINGS QUE SE USARAN COMO COMANDOS
public class Comandos {
	public static final String INICIA = "inicia",	
							   ADELANTE = "adelante",
							   ATRAS = "atras",
							   BUSCA = "buscar",
							   GUARDA = "guardar",
							   ECUALIZAR = "ecualizar",
							   ECUALIZARGB = "ecualizarRGB",
							   ECUALIZAGRIS = "ecualizarGRIS",
							   HISTA = "histograma anterior",
							   HISTN = "histograma nuevo",
							   INVB = "inversion binaria",
							   INVF = "inversion fotografica",
							   ADD = "adicionar",
							   SUS = "sustraer",
							   ACOLLAGE = "agregar imagen al collage",
							   GCOLLAGE = "generar el collage",
							   BUSCARRUTA = "busca ruta para guardar imagen",
							   GUARDARREALMENTE = "guardar la imagen",
							   GUARDO ="se debe guardar la imagen",
							   BUSCARSUS = "buscar imagen para sustraer o adicionar",
							   REGENERAR = "regenerar collage",
							   RESET = "resetear collage",
							   ROTARIZQUIERDA ="rotar a la izquierda",
							   ROTARDERECHA ="rotar a la derecha",
							   ESPEJO="espejo",
							   MODA = "filtro moda",
							   MEDIA = "filtro media",
							   MEDIANA = "filtro mediana",
							   GAUSS = "filtro gaussiano",
							   N1="n1",
							   N2="n2",
							   N3="n3",
						   	   N4="n4",
						 	   N5="n5",
							   N6="n6",
							   N7="n7",
							   N8="n8",
							   N9="n9",
							   LP4 = "filtro laplaciano4",
							   LP8 = "filtro laplaciano8",
							   PRE = "filtro prewitt",
							   SOBEL="filtro sobel",
							   ROBERT="filtro roberts",
							   EROSION = "erosiona",
							   DILATACION ="dilata",
							   VENTANAESTRUC = "salir ventana de ele",
							   GENERARESTRUC = "genera elemento estruc",
							   DEFINIRESTRUC= "define elemento estruc";
}